.TH EZSCP 1 "EASY SECURE COPY" "29 OCTOBER 2017"
.TH OVERVIEW
.B ezscp
- an easy front end interface for scp
.TH SYNOPSIS
.B ezscp
.TH DETAILS
.B ezscp
- "easy secure copy" - is an interactive shell script designed to make running scp(1) easier.
.TH DIAGNOSTICS
.B ezscp
returns 0 on successful completion, 1 on an error while running the script or other abnormal exit, and 2 if scp did not exit with 0 (scp failure).
.TH DEPENDENCIES
.B ezscp
depends on touch, scp, and must be run on bash.
.TH AUTHOR
Sam Ave <https://github.com/sam-irl/ezscp>
.TH LICENSE
MIT
