.TH EZSCP 1 "EASY SECURE COPY" "29 OCTOBER 2017"
.SH OVERVIEW
.B ezscp
- an easy front end interface for scp
.SH SYNOPSIS
.B ezscp
.SH DETAILS
.B ezscp
- "easy secure copy" - is an interactive shell script designed to make running scp(1) easier.
.SH DIAGNOSTICS
.B ezscp
returns 0 on successful completion, 1 on an error while running the script or other abnormal exit, and 2 if scp did not exit with 0 (scp failure).
.SH DEPENDENCIES
.B ezscp
depends on touch, scp, and must be run on bash.
.SH AUTHOR
Sam Ave <https://github.com/sam-irl/ezscp>
.SH LICENSE
MIT
